/**
 * pricingData.js - Pricing packages and included perks for Colloquium AI
 */
export const PRICING_PLANS = [
  {
    id: "1",
    name: "Free",
    badge: "Trial",
    description: "Ideal for experiencing the AI interview format first-hand",
    price: "₹0",
    billing: "Forever free trial",
    credits: 100,
    popular: false,
    features: [
      "1 Full AI Interview session",
      "Standard voice simulation",
      "Core evaluation report",
      "Basic role-based questions",
    ],
    buttonText: "Start Free",
  },
  {
    id: "2",
    name: "Basic",
    badge: "Essential",
    description: "Great for quick brush-ups and targeted interview practice",
    price: "₹199",
    billing: "One-time payment",
    credits: 1000,
    popular: false,
    features: [
      "Up to 10 AI Interviews",
      "Realistic voice conversation",
      "Resume parsing & extraction",
      "Comprehensive score breakdown",
      "Credits never expire",
    ],
    buttonText: "Get Basic",
  },
  {
    id: "3",
    name: "Standard",
    badge: "Most Popular",
    description: "Best for active job seekers targeting multiple technical roles",
    price: "₹899",
    billing: "One-time payment",
    credits: 5000,
    popular: true,
    features: [
      "Up to 50 AI Interviews",
      "Elena & Marcus AI voice options",
      "In-depth Technical & HR modes",
      "Detailed question feedback",
      "Priority question generation",
      "Print & PDF evaluation reports",
    ],
    buttonText: "Upgrade to Standard",
  },
  {
    id: "4",
    name: "Premium",
    badge: "Best Value",
    description: "Maximum preparation package for senior roles and career shifts",
    price: "₹1,999",
    billing: "One-time payment",
    credits: 10000,
    popular: false,
    features: [
      "100+ AI Interviews",
      "Unlimited Resume analyses",
      "All interviewer avatars & voices",
      "Deep behavioral & tech metrics",
      "Unlimited PDF report downloads",
      "Priority customer assistance",
    ],
    buttonText: "Get Premium",
  },
];
